### ISSUE TITLE
一定要在 .vimrc 設定 g:ime_plugins 才有作用

### ISSUE THREAD

**Issue by redeyes2015** [pi314/ime.vim#59]
目前的版本 (Version 0.43.1) 如果在 .vimrc 沒有設定 g:ime_plugins，用 `,,` 切換輸入法會沒有作用，`,m` 也會顯示空的列表，`echo g:ime_plugins` 的確如文件所說是 `['builtin-boshiamy', 'builtin-kana', 'builtin-chewing', 'builtin-unicode']`

但是在 .vimrc 加上 `let g:ime_plugins = [ 'builtin_boshiamy' ]` 之後，切換輸入法就會有作用了

平台: ubuntu 18:04 ，有用 docker 實驗過從乾淨的環境安裝 vim、ime.vim 之後也有一樣的狀況

BTW, 感謝你開發這個 plugin!

**Comment by pi314** [comment]
感謝使用！

追查後發現，這個問題是從 279033b，開始 plugin 的名稱不能包含 `-`，但 `g:ime_plugins` 的預設值全都是有 `-` 的，沒有跟著換成 `_`

就默默的爆炸了 ˊ_>ˋ

已在 1d486f0 (Version 0.43.2) 修正，如果更新後沒問題的話請再跟我說一聲 :D

**Comment by redeyes2015** [comment]
確認 OK 囉~ 感謝!
