### ISSUE TITLE
使用空字串取消預設的keymap

### ISSUE THREAD

**Issue by rlf23240** [pi314/ime.vim#60]
首先非常感謝您開發這個plugin，非常的簡單好用！
以下是我碰到的小問題

由於在neovim底下我更傾向於使用lua的api綁定按鍵 調整功能以及解決衝突，
不知是否能夠加入類似如下的判斷：

```
if g:ime_toggle_english != ''
    execute 'inoremap <expr> '. g:ime_toggle_english .' (pumvisible() ? "<C-Y>" : "") . ime#toggle_english()'
endif
```

或是加入一個額外的選項來達成這個效果，避免使用者亂塞奇怪的值
我明白這是一個比較不尋常的需求，但在解決類似 #36 這類的問題上，
這樣的選項能夠在提出示警後將決定權交給使用者

另外一個小小的bug，[這裡](https://github.com/pi314/ime.vim/blob/69b5054ae59030ebbd4e3addd03b4b82aea86608/plugin/ime.vim#L63)第二個條件是否應改為 `type(g:ime_menu) != type('')`？

**Comment by pi314** [comment]
> 避免使用者亂塞奇怪的值

看了才發現當時沒有考慮到這點，會帶給 `execute` 的東西都應該要先檢查過才對

**Comment by pi314** [comment]
https://github.com/pi314/ime.vim/commit/da7e159bb0489caa0eab3dde96c79d038e18553e
不麻煩的話，可以試試看這個 patch 有沒有解決問題嗎？
原本的寫法在我這裡就算 `let g:ime_toggle_english = ''` 也神奇的沒有出現錯誤訊息

若 patch ok 的話，你可以發 pull request 留名，也可以說 ok 就好，我把它 merge 回去

**Comment by rlf23240** [comment]
> 原本的寫法在我這裡就算 `let g:ime_toggle_english = ''` 也神奇的沒有出現錯誤訊息

他應該是把 `(pumvisible()` 當成要綁定的按鍵組合了 所以也沒報錯
