### ISSUE TITLE
請問如何輸入中文

### ISSUE THREAD

**Issue by trevim99** [pi314/ime.vim#62]
您好

謝謝開發嘸蝦米的輸入程式，請問我已經安裝完成了ime.vim (已可以在gvim 9.0打 help ime.vim 看到說明文件)

請問我要怎麼使用 ime.vim 輸入中文? 謝謝您

我的環境是 WINDOWS 10+ gvim 9.0

謝謝您

**Comment by pi314** [comment]
Hi Trevim,

我還沒有用過 vim9，這個 plugin 很可能和它不相容

可以按 `,,` 以後試試看能不能輸入嘸蝦米字根

**Comment by trevim99** [comment]
謝謝您，我按,, 就可以在GVIM9.0用嘸蝦米輸入中文了。
您的程式，真是很棒的VIM 外掛，謝謝您

**Comment by trevim99** [comment]
請問自訂字根表要怎麼呼叫出來?

已經做了一個檔案在   ～/.boshiamy.table
但是在InsertMode的中文輸入模式下 ，打  face 或是 ,face 均無反應
也試過把 let g:ime_boshiamy_custom_table = '~/.boshiamy.table' 這行加在 _vimrc
但亦無反應。 
謝謝

**Comment by trevim99** [comment]
請問　statusline　要怎麼設定？　試了說明中的
set statusline=%<%{ime#mode()}%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
及
function! IMEStatusString ()
    if exists('*ime#mode')
        return ime#mode()
    endif
    return ''
endfunction
set statusline=%{IMEStatusString()}

已分別把上面的指令個別加在＿vimrc 
但是仍然無法顯示輸入法的狀態，請問該怎麼做呢?
謝謝您

**Comment by pi314** [comment]
自訂字根表的問題，在 Windows 上可以試試把檔名改成 _boshiamy_table，路徑裡的 `/` 改成 `\`

statusline 的問題，可以先試試手動執行 `:echo ime#mode()` 指令，確認它能拿得到目前最新的狀態
如果你的 vim 版本比 7.4.1711 還新，應該可以直接在 statusline 裡面使用 `ime#icon()` (README 沒有更新，寫的是 `ime#mode()`
